#' Generates the file name look-up table
#'
#' Generate a look-up table connecting the PDF file names to the temporary file
#' names generated by the shiny app.
#'
#' @param file_properties shiny defined properties of uploaded files
#'
#' @noRd

gen_file_name_lookup <- function(file_properties) {
  file_names_pdf <- file_names_temp <- NULL

  file_names_pdf  <- basename(file_properties$name)
  file_names_temp <- basename(file_properties$datapath)

  # Name file objects
  # names(file_names_pdf)  <- "file_name_pdf"
  # names(file_names_temp) <- "file_name_temp"

  # Combine temporary and actual file names into look-up table
  output.df <- dplyr::bind_cols(
    file_names_pdf,
    file_names_temp
  ) %>%
    dplyr::rename(
      file_name_pdf  = '...1',
      file_name_temp = '...2'
    )

  output.df
}


#' Generate CausalityExtraction table
#'
#' Generate output table of the CausalityExtraction function.
#'
#' @param file_properties shiny defined properties of uploaded files
#'
#' @noRd

gen_causality_extraction_table <- function(file_properties) {
  file_name <- file_name_pdf <- NULL

  # Create look-up table
  lookup_table <- gen_file_name_lookup(file_properties)

  # Define uploaded file paths
  file_paths <- file_properties$datapath

  # Generate output table, with temporary file names
  output_table <- CausalityExtraction(file_path = file_paths)

  # Replace temporary file names with uploaded file names
  output_table <- output_table %>%
    dplyr::left_join(
      y  = lookup_table,
      by = c("file_name" = "file_name_temp")
    ) %>%
    dplyr::select(-file_name) %>%                  # Drop temporary file name
    dplyr::rename(file_name = file_name_pdf) %>%   # Rename actual file name col
    dplyr::select(file_name, dplyr::everything())

  output_table
}
